spring:
  application:
    name: integration-demo

server:
  port: 8081

nacos:
  config:
    server-addr: 172.0.0.1:8848

dubbo:
  provider:
    group: demo
    version: 1.0.0
    timeout: 15000
    retries: 1

  consumer:
    check: false
    tag:
  application:
    id: integration-demo
    name: integration-demo
    qos-port: 22224
    qos-enable: true

  scan:
    base-packages: com.example.demo.*

  registry:
    id: nacos
    protocol: nacos
    address: 172.0.0.1:8848

  protocol:
    id: dubbo
    name: dubbo
    port: 20884
    dispatcher: all
    threadpool: fixed
    threads: 80
    iothreads: 40